export async function createSprint(args: any): Promise<any> {
  return {
    message: `Created sprint "${args.title}".`,
    content: {
      sprint: {
        name: args.name,
        goal: args.goal,
        startDate: args.startDate,
        endDate: args.endDate,
        issues: args.issues,
      },
    },
  };
}

export const createSprintFn = () => {
  return {
    name: "create_sprint",
    description: "Creates a new sprint in a project management system.",
    parameters: {
      type: "object",
      properties: {
        name: {
          type: "string",
          description: "name of the sprint",
        },
        goal: {
          type: "string",
          description:
            "goal of the sprint, can be provided by user or generated by assistant",
        },
        startDate: {
          type: "string",
          description:
            "starting date of the sprint, it should be in this format: 2025-07-24T00:00:00+00:00",
        },
        endDate: {
          type: "string",
          description:
            "ending date of the sprint, it should be in this format: 2025-07-24T23:59:59+00:00",
        },
        issues: {
          type: "array",
          description: "List of issues to be included in the sprint",
          items: {
            type: "object",
            properties: {
              id: {
                type: "string",
                description: "Unique ID of the issue",
              },
              title: {
                type: "string",
                description: "Title of the issue",
              },
            },
            required: ["id", "title"],
          },
        },
        createInLocalOnly: {
          type: "boolean",
          description:
            "If true, creates locally instead of syncing to Jira/Linear",
        },
      },
      required: ["name", "goal", "startDate", "endDate", "createInLocalOnly"],
    },
  };
};
