import { getRelevantIssues } from "../utils/getRelevantIssues";

export async function findRelevantIssues(args: any): Promise<any> {
  const issues = await getRelevantIssues(args.goal);
  return {
    message: `Found issues relevant to goal: "${args.goal}".`,
    content: {
      issues,
    },
  };
}

export const findRelevantIssuesFn = () => {
  return {
    name: "find_relevant_issues",
    description:
      "Finds the relavant issues according to sprint goal by applying a similarity search on issue embeddings.",
    parameters: {
      type: "object",
      properties: {
        goal: {
          type: "string",
          description:
            "goal of the sprint, can be provided by user or generated by assistant",
        },
      },
      required: ["goal"],
    },
  };
};
